# Generated by Django 2.2.4 on 2019-12-04 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonitorInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=50, verbose_name='用户ID')),
                ('alertName', models.CharField(max_length=200, verbose_name='报警名称')),
                ('timestamp', models.DateTimeField()),
                ('alertState', models.CharField(max_length=50, verbose_name='报警状态')),
                ('dimensions', models.CharField(max_length=200, verbose_name='发生报警的对象')),
                ('expression', models.CharField(max_length=200, verbose_name='报警条件')),
                ('curValue', models.CharField(max_length=50, verbose_name='报警发生或恢复时监控项的当前值')),
                ('metricName', models.CharField(max_length=100, verbose_name='监控项名称')),
                ('metricProject', models.CharField(max_length=100, verbose_name='产品名称')),
            ],
            options={
                'verbose_name': '监控',
                'verbose_name_plural': '监控',
            },
        ),
    ]
