# Generated by Django 2.2.4 on 2019-12-04 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CallBack', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monitorinfo',
            options={},
        ),
    ]
